/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import static java.lang.Integer.parseInt;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.bean.venda_bean;
import modelo_query.dao.VendasDao;

/**
 *
 * @author 963478
 */
public class tela_6 extends javax.swing.JFrame {

    /**
     * Creates new form tela_6
     */
    public tela_6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DINHEIRO = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pagamentos = new javax.swing.JLabel();
        hoje = new javax.swing.JLabel();
        dinheiro = new javax.swing.JLabel();
        cartao = new javax.swing.JLabel();
        cheque = new javax.swing.JLabel();
        troco = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        obs = new javax.swing.JTextField();
        c5 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        c4 = new javax.swing.JTextField();
        finalizar = new javax.swing.JButton();
        finalizar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        DINHEIRO.setBackground(new java.awt.Color(255, 255, 255));
        DINHEIRO.setForeground(new java.awt.Color(255, 255, 255));
        DINHEIRO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 105, 255));

        pagamentos.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        pagamentos.setForeground(new java.awt.Color(255, 255, 255));
        pagamentos.setText("Pagamentos");

        hoje.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        hoje.setForeground(new java.awt.Color(255, 255, 255));
        hoje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hoje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(pagamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(hoje, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pagamentos)
                    .addComponent(hoje, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        DINHEIRO.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 120));

        dinheiro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dinheiro.setText("DINHEIRO:");
        DINHEIRO.add(dinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        cartao.setBackground(new java.awt.Color(0, 0, 0));
        cartao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cartao.setText("CARTÃO:");
        DINHEIRO.add(cartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        cheque.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cheque.setText("CHEQUE:");
        DINHEIRO.add(cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        troco.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        troco.setText("TROCO:");
        DINHEIRO.add(troco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        total.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        total.setText("TOTAL:");
        DINHEIRO.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label.setText("Obs.:");
        DINHEIRO.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 166, -1, -1));

        obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obsActionPerformed(evt);
            }
        });
        DINHEIRO.add(obs, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 164, 330, 130));
        DINHEIRO.add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 150, 30));

        c1.setText("1");
        DINHEIRO.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, 30));

        c2.setText("2");
        DINHEIRO.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 150, 30));

        c3.setText("3");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        DINHEIRO.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 150, 30));

        c4.setText("1");
        DINHEIRO.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 150, 30));

        finalizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        finalizar.setText("Salvar");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });
        DINHEIRO.add(finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 130, 40));

        finalizar1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        finalizar1.setText("Somar");
        finalizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizar1ActionPerformed(evt);
            }
        });
        DINHEIRO.add(finalizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DINHEIRO, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DINHEIRO, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obsActionPerformed

    private void finalizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizar1ActionPerformed
        // TODO add your handling code here:
        String observacao = obs.getText();
        
        int a,b,c,d,e;
        a = parseInt(c1.getText());
        b = parseInt(c2.getText());
        c = parseInt(c3.getText());
        d = parseInt(c4.getText());
        
        e = a+b+c+d;
        
        c5.setText(" " + e);
        
        Date dataAtual = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dataFormatada = sdf.format (dataAtual);
        hoje.setText(""+dataFormatada);
        
        venda_bean v = new venda_bean();
        VendasDao dao = new VendasDao();
        v.setdata_venda(""+dataFormatada);
        v.settotal_venda(e);
        v.setobs(observacao);
        dao.create(v);
    }//GEN-LAST:event_finalizar1ActionPerformed

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalizarActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DINHEIRO;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JTextField c4;
    private javax.swing.JTextField c5;
    private javax.swing.JLabel cartao;
    private javax.swing.JLabel cheque;
    private javax.swing.JLabel dinheiro;
    private javax.swing.JButton finalizar;
    private javax.swing.JButton finalizar1;
    private javax.swing.JLabel hoje;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label;
    private javax.swing.JTextField obs;
    private javax.swing.JLabel pagamentos;
    private javax.swing.JLabel total;
    private javax.swing.JLabel troco;
    // End of variables declaration//GEN-END:variables
}
